<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,1,1,'5ZCN6Iy26I2f6JCD');
$cfg_Cs[2]=array(0,1,1,'6Iy25Lia5Yqo5oCB');
$cfg_Cs[3]=array(0,1,1,'6Iy25Lq66Iy25LqL');
$cfg_Cs[4]=array(0,1,1,'6Iy25ZGo5YiK');
$cfg_Cs[5]=array(0,1,1,'5LuZ6Iy25paH5YyW');
$cfg_Cs[6]=array(0,1,1,'6Iy25pm65bqT');
$cfg_Cs[7]=array(0,1,1,'6Iy25Z2b5ZGo6L65');
$cfg_Cs[8]=array(1,1,1,'6KW/5Y2X6Iy25Yy6');
$cfg_Cs[9]=array(1,1,1,'5Y2O5Y2X6Iy25Yy6');
$cfg_Cs[10]=array(1,1,1,'5rGf5Y2X6Iy25Yy6');
$cfg_Cs[11]=array(1,1,1,'5rGf5YyX6Iy25Yy6');
?>